# Feeds from http://showrss.info/?cs=feeds
# Related http://dancingborg.blogspot.com.au/2011/06/ubuntu-file-server-part-12-flexget.html

presets:

  tvtorrent:
    deluge:
      content_filename: '%(series_name)s - %(series_id)s'
      movedone: /media/PNY/series/%(series_name)s/Season %(series_season)d/
      main_file_only: yes
      queuetotop: yes
      automanaged: true
      user: username
      pass: password

  showexists:
    exists_series: /media/PNY/TV Shows

  sdtv:
    quality: hdtv <720p

tasks:
 
# Working as of 13/05/2011
  The Big Bang Theory:
    rss: http://showrss.karmorra.info/feeds/5.rss
    series:
      - The Big Bang Theory
    preset:
      - tvtorrent
      - showexists

# Working as of 13/05/2011
  Grey's Anatomy:
    rss: http://showrss.karmorra.info/feeds/34.rss
    series:
      - Grey's Anatomy
    preset:
      - tvtorrent
      - showexists

# Working as of 12/10/2013
  Modern Family:
    rss: http://showrss.info/feeds/221.rss
    series:
      - Modern Family
    preset:
      - tvtorrent
      - showexists
      - sdtv

# Show to return in 2012; feed is slightly outdated
# Only gets to S04E01 when it should have been up to S04E06 
  Packed to the Rafters:
    rss: http://showrss.karmorra.info/feeds/203.rss
    series:
      - Packed to the Rafters
    preset:
      - tvtorrent
      - showexists

# Working as of 13/05/2011
  Gossip Girl:
    rss: http://showrss.karmorra.info/feeds/32.rss
    series:
      - Gossip Girl
    preset:
      - tvtorrent
      - showexists

# Working as of 17/05/2011
  How I Met Your Mother:
    rss: http://showrss.karmorra.info/feeds/37.rss
    series:
      - How I Met Your Mother
    preset:
      - tvtorrent
      - showexists
# Working as of 17/05/2011
  Glee:
    rss: http://showrss.karmorra.info/feeds/31.rss
    series:
      - Glee
    preset:
      - tvtorrent
      - showexists

# Working as of 17/05/2011
  Bones:
    rss: http://showrss.karmorra.info/feeds/6.rss
    series:
      - Bones
    preset:
      - tvtorrent
      - showexists

# Working as of 17/05/2011
  Castle:
    rss: http://showrss.karmorra.info/feeds/109.rss
    series:
      - Castle
    preset:
      - tvtorrent
      - showexists

# Working as of 17/05/2011
  Cops:
    rss: http://showrss.karmorra.info/feeds/125.rss
    series:
      - Cops
    preset:
      - tvtorrent
      - showexists

# Working as of 17/05/2011
  MythBusters:
    rss: http://showrss.karmorra.info/feeds/46.rss
    series:
      - MythBusters
    preset:
      - tvtorrent
      - showexists

# Working as of 20/05/2011
  Mad Men:
    rss: http://showrss.karmorra.info/feeds/42.rss
    series:
      - Mad Men
    preset:
      - tvtorrent
      - showexists

# Not working as of 06/06/2011: no torrents at end of link
#  Doctor Who:
#    rss: http://showrss.karmorra.info/feeds/103.rss
#    series:
#      - Doctor Who
#    preset:
#      - tvtorrent
#      - showexists

#Working as of 28/06/2011
  NCIS:
    rss: http://showrss.karmorra.info/feeds/47.rss
    series:
      - NCIS
    preset:
      - tvtorrent
      - showexists

#Working as of 28/06/2011
  Man vs. Wild:
    rss: http://showrss.karmorra.info/feeds/126.rss
    series:
      - Man vs. Wild
    preset:
      - tvtorrent
      - showexists

#Working as of 7/08/2011
  Top Gear:
    rss: http://showrss.karmorra.info/feeds/117.rss
    series:
      - Top Gear
    preset:
      - tvtorrent
      - showexists
#Working as of 17/08/2011 but no new shows
  QI:
    rss: http://showrss.karmorra.info/feeds/240.rss
    series:
      - QI
    preset:
      - tvtorrent
      - showexists

#Working as of 17/08/2011
  Law & Order UK:
    rss: http://showrss.karmorra.info/feeds/244.rss
    series:
      - Law & Order UK
    preset:
      - tvtorrent
      - showexists
