templates:

  tvtorrent:
    exists_series: /media/Series/
    magnets: no
    deluge:
      username: osiris
      password: osiris
      main_file_only: yes
      main_file_ratio: 0.85
      hide_sparse_files: no
      keep_subs: no
      automanaged: true
      content_filename: '%(series_name)s - %(series_id)s'
      movedone: /media/Series/%(series_name)s/Season %(series_season)d/
      ratio: 0.0001
      removeatratio: yes

tasks:

  Castle (2009):
    rss: http://showrss.info/show/53.rss
    series:
      - Castle (2009)
    preset:
      - tvtorrent
