# Feeds from http://showrss.info/?cs=feeds
# Related http://dancingborg.blogspot.com.au/2011/06/ubuntu-file-server-part-12-flexget.html

presets:

  tvtorrent:
    magnets: no
    deluge:
      content_filename: '%(series_name)s - %(series_id)s'
      movedone: /media/Series/%(series_name)s/Season %(series_season)d/
      main_file_only: yes
      queuetotop: yes
      automanaged: true
      user: osiris
      pass: osiris
    quality: hdtv <720p
    exists_series: /media/Series/

tasks:

# Working 16/10/2013
  Modern Family:
    rss: http://showrss.info/feeds/221.rss
    series:
      - Modern Family
    preset:
      - tvtorrent

# Working 16/10/2013
  Suits:
    rss: http://showrss.info/feeds/367.rss
    series:
      - Suits
    preset:
      - tvtorrent

# Working 16/10/2013
  Castle (2009):
    rss: http://showrss.info/feeds/109.rss
    series:
      - Castle (2009)
    preset:
      - tvtorrent

# Working 16/10/2013
  Downton Abbey:
    rss: http://showrss.info/feeds/383.rss
    series:
      - Downton Abbey
    preset:
      - tvtorrent

# RSS feed gets 404 as of 16/10/2013
  Game of Thrones:
    rss: http://showrss.info/feeds/350.rss
    series:
      - Game of Thrones
    preset:
      - tvtorrent


# Working 16/10/2013
  Grey's Anatomy:
    rss: http://showrss.info/feeds/34.rss
    series:
      - Grey's Anatomy
    preset:
      - tvtorrent

# Working 16/10/2013
  How I Met Your Mother:
    rss: http://showrss.info/feeds/37.rss
    series:
      - How I Met Your Mother
    preset:
      - tvtorrent

# Working 16/10/2013
  Mad Men:
    rss: http://showrss.info/feeds/42.rss
    series:
      - Mad Men
    preset:
      - tvtorrent

# Working 16/10/2013
  The Blacklist:
    rss: http://showrss.info/feeds/609.rss
    series:
      - The Blacklist
    preset:
      - tvtorrent

# Working 16/10/2013
  The Big Bang Theory:
    rss: http://showrss.info/feeds/5.rss
    series:
      - The Big Bang Theory
    preset:
      - tvtorrent

# Working 19/10/2013
  America's Next Top Model:
    rss: http://showrss.info/feeds/113.rss
    series:
      - America's Next Top Model
    preset:
      - tvtorrent

# Working 19/10/2013
  Boardwalk Empire:
    rss: http://showrss.info/feeds/292.rss
    series:
      - Boardwalk Empire
    preset:
      - tvtorrent

# Working 19/10/2013
  Homeland:
    rss: http://showrss.info/feeds/400.rss
    series:
      - Homeland
    preset:
      - tvtorrent

# Working 6/11/2013
  Elementary:
    rss: http://showrss.info/feeds/485.rss
    series:
      - Elementary
    preset:
      - tvtorrent
