templates:

  tvtorrent:
    exists_series: /media/Series/
    magnets: no
    deluge:
      username: osiris
      password: osiris
      main_file_only: yes
      main_file_ratio: 0.85
      hide_sparse_files: no
      keep_subs: no
      automanaged: true
      content_filename: '%(series_name)s - %(series_id)s'
      movedone: /media/Series/%(series_name)s/Season %(series_season)d/
      ratio: 0.0001
      removeatratio: yes
tasks:

  showRSS:
    rss: http://showrss.info/user/6892.rss?magnets=true&namespaces=true&name=clean&quality=sd&re=yes
    series:
      - America's Next Top Model
      - Castle (2009)
      - Elementary
      - Game of Thrones
      - Grey's Anatomy
      - Homeland
      - House of Cards (2013)
      - Modern Family
      - Mythbusters
      - Scandal (2012)
      - Sherlock
      - Suits
      - The Big Bang Theory
      - The Blacklist
      - Top Gear
    template:
      - tvtorrent
