presets:

  tvtorrent:
    exists_series: /media/Series/
    magnets: no
    deluge:
      user: osiris
      pass: osiris
      main_file_only: yes
      automanaged: true
      content_filename: '%(series_name)s - %(series_id)s'
      movedone: /media/Series/%(series_name)s/Season %(series_season)d/
      ratio: 0.0001
      removeatratio: yes

  movie:
    exists_movie: /media/MoviesHD/
    deluge:
      user: osiris
      pass: osiris
      automanaged: true
      content_filename: "{{imdb_name}} ({{imdb_year}})"
      movedone: /media/MoviesHD/
      ratio: 0.0001
      removeatratio: yes

tasks:

  showRSS:
    rss: http://showrss.info/rss.php?user_id=227669&hd=0&proper=1&magnets=false
    series:
      - Modern Family
      - Suits
      - Castle (2009)
      - Downton Abbey
      - Game of Thrones
      - Grey's Anatomy
      - How I Met Your Mother
      - Mad Men
      - The Blacklist
      - The Big Bang Theory
      - America's Next Top Model
      - Boardwalk Empire
      - Homeland
      - Elementary
      - Scandal (2012)
      - House of Cards (2013)
      - Glee
      - MythBusters
      - Sherlock
      - Top Gear
    preset:
      - tvtorrent

  YTS:
    rss: http://yts.re/rss/0/1080p/All/7
    accept_all: yes
    seen_movies: strict
    imdb_required: yes
    imdb:
      reject_genres:
        - horror
        - documentary
    limit_new: 1
    interval: 1 days
    preset:
      - movie
