templates:

  tvtorrent:
    exists_series: /media/Series/
    magnets: no
    deluge:
      username: osiris
      password: osiris
      main_file_only: yes
      main_file_ratio: 0.85
      hide_sparse_files: no
      keep_subs: no
      automanaged: true
      content_filename: '%(series_name)s - %(series_id)s'
      movedone: /media/Series/%(series_name)s/Season %(series_season)d/
      ratio: 0.0001
      removeatratio: yes
tasks:

  showRSS:
    rss: http://showrss.info/rss.php?user_id=227669&hd=null&proper=1&magnets=false
    series:
      - Modern Family
      - Suits
      - Castle (2009)
      - Downton Abbey
      - Game of Thrones
      - Grey's Anatomy
      - How I Met Your Mother
      - Mad Men
      - The Blacklist
      - The Big Bang Theory
      - America's Next Top Model
      - Boardwalk Empire
      - Homeland
      - Elementary
      - Scandal (2012)
      - House of Cards (2013)
      - Glee
      - MythBusters
      - Sherlock
      - Top Gear
    template:
      - tvtorrent
