# Feeds from http://showrss.info/?cs=feeds
# Related http://dancingborg.blogspot.com.au/2011/06/ubuntu-file-server-part-12-flexget.html

presets:

  tvtorrent:
    deluge:
      content_filename: '%(series_name)s - %(series_id)s'
      movedone: /media/Series/%(series_name)/Season %(series_season)/
      main_file_only: yes
      queuetotop: yes
      automanaged: true
      user: deluge
      pass: deluge

  showexists:
    exists_series: /media/Series/

  sdtv:
    quality: hdtv <720p

tasks:

# Working as of 12/10/2013
  Modern Family:
    rss: http://showrss.info/feeds/221.rss
    series:
      - Modern Family
    preset:
      - tvtorrent
      - showexists
      - sdtv

